accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name="mainapp"

urlpatterns = [
    path('<str:category_name>/', views.placelist, name='placelist'),
    path('<str:category_name>/<int:place_id>/', views.detail, name='detail'),
    path('<str:category_name>/new/', views.new, name='new'),
    path('<str:category_name>/<int:place_id>/update/', views.update, name='update'),
    path('<str:category_name>/<int:place_id>/delete/', views.delete, name='delete'),
]

studyplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import mainapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.views.home, name='home'),
    path('placelist/', include('mainapp.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)

class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('이메일 주소를 기본값으로 가지고 있어야 합니다.')

        user = self.model(
            email=self.normalize_email(email),
            username = username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length=30, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from django.contrib.auth import get_user_model
User = get_user_model()

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'username')

    def clean_password(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다.")
        return password1

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password',
                  'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib import auth
from .forms import UserCreationForm

User = get_user_model()

# Create your views here.

# def signup(request):
#     if request.method == 'POST':
#         if request.POST['password1'] == request.POST['password2']:
#             try:
#                 user = User.objects.get(username=request.POST['username'])
#                 return render(request, 'accounts/signup.html', {'error': 'Username has already been taken'})
#             except User.DoesNotExist:
#                 user = User.objects.create_user(
#                     request.POST['username'], password=request.POST['password1'])
#                 auth.login(request, user)
#                 return redirect('home')
#         else:
#             return render(request, 'accounts/signup.html', {'error': 'Passwords must match'})
#     else:
#         return render(request, 'accounts/signup.html')

# def signup(request):
#     form = UserCreationForm(request.POST)
#     if request.method == 'POST':
#         if form.is_valid():
#             form.save()
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password1']
#             user = auth.authenticate(username = email, password = password)
#             auth.login(request, user)
#             return redirect('home')
#     else:
#         form = UserCreationForm()
#     return render(request, 'accounts/signup.html', {'form': form})

def signup(request):
    form = UserCreationForm(request.POST)
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            if form.is_valid():
                form.save()
                email = form.cleaned_data['email']
                password = form.cleaned_data['password1']
                user = auth.authenticate(username = email, password = password)
                auth.login(request, user)
                return redirect('home')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords must match'})
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(request, username=email, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('home')
    return render(request, 'accounts/signup.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">

{% if error %}
{{ error }}
{% endif %}


<!-- <form method="POST" action="{% url 'accounts:login'%}">

    {% csrf_token %}
    Username:
    <br>
    <input name="username" type="text" value="">
    <br>
    Password:
    <br>
    <input name="password" type="password" value="">
    <br>
    <br>
    <input class="btn btn-primary" type="submit" value="Login">
</form> -->

<div class="login-box">
    <h1 class="login-title">로그인</h1>

    <form class='login-form' method="POST" action="{% url 'accounts:login' %}">

        {% csrf_token %}
        <div class="login-input-box">
        <input name="email" type="text" value="" placeholder="이메일">
        </div>
 
        <div class="login-input-box">
        <input name="password" type="password" value="" placeholder="비밀번호">
        </div>

        <input class="login-button" type="submit" value="로그인">
    
    </form>
    <div class="login-etc-box">
        <a class="login-find-pw">비밀번호 찾기</a><span class="login-etc-separator">|</span><a href="{% url 'accounts:signup' %}">회원가입</a>
    </div>
    <div class="login-kakao-box">
        <img class="login-kakao-logo" src="{% static 'accounts/images/kakao.png' %}">
        <span>카카오로 로그인 하기</span>
    </div>
    <div class="login-google-box">
        <img class="login-google-logo" src="{% static 'accounts/images/google.png' %}">
        <span>구글로 로그인 하기</span>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}">

{% if error %}
{{ error }}
{% endif %}

{% if errors %}
{{ errors }}
{% endif %}

<div class="signup-box">
    <h1 class="signup-title">회원가입</h1>

    <form class='signup-form' method="POST" action="{% url 'accounts:signup' %}">

        {% csrf_token %}
        <div class="signup-input-box">
            <div class="siginup-text-item">아이디</div>
        <input name="username" type="text" value="" placeholder="아이디 입력(5~11자)">
        </div>
        <div class="signup-input-box">
            <div class="siginup-text-item">이메일</div>
            <input name="email" type="text" value="" placeholder="이메일">
        </div>
        <div class="signup-input-box">
        <div class="siginup-text-item">비밀번호</div>
        <input name="password1" type="password" value="" placeholder="비밀번호 입력(숫자, 영문, 특수문자 조합 6자 이상)">
        </div>
        <div class="signup-input-box">
            <div class="siginup-text-item">비밀번호 확인</div>
            <input name="password2" type="password" value="" placeholder="비밀번호 확인">
        </div>

        <input class="signup-button" type="submit" value="확인">
    </form>
</div>

{% endblock %}