accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name="mainapp"

urlpatterns = [
    path('<str:category_name>/', views.placelist, name='placelist'),
    path('<str:category_name>/<int:place_id>/', views.detail, name='detail'),
    path('<str:category_name>/new/', views.new, name='new'),
    path('<str:category_name>/<int:place_id>/update/', views.update, name='update'),
    path('<str:category_name>/<int:place_id>/delete/', views.delete, name='delete'),
]

studyplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import mainapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.views.home, name='home'),
    path('placelist/', include('mainapp.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from email.headerregistry import Address
from email.policy import default
from unicodedata import category
from django.db import models
from django.urls import reverse
from uuid import uuid4
from django.utils import timezone
import os

class Category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home")

class Place(models.Model):

    name = models.CharField(max_length=100)  #place 이름
    address = models.CharField(max_length=150, default="", blank=True)   #주소
    phone_number = models.CharField(max_length=30, default="", blank=True)   #전화번호
    business_hour = models.CharField(max_length=100, default="", blank=True)   #영업시간
    photo = models.ImageField(upload_to="place/photo", blank=True)   #place 이미지
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    @property
    def get_photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url
        else:
            return '/static/mainapp/images/notfoundimage.png'

mainapp/forms.py
from django import forms
from .models import Category, Place

class PlaceNew(forms.ModelForm):
    class Meta:
        model = Place
        fields = ['name','address', 'phone_number', 'business_hour', 'photo', 'category']

mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator

from .models import Place, Category
from .forms import PlaceNew


def home(request):
    return render(request, 'mainapp/home.html')

def placelist(request, category_name):
    categories = Category.objects.all()
    category = get_object_or_404(Category, name=category_name)
    places = Place.objects.filter(category=category)

    paginator = Paginator(places, 6)
    page = request.GET.get('page',1)
    page_obj = paginator.page(page)
    page_range = paginator.get_elided_page_range(number=page)
    context = {
        'places':places,'page_range':page_range, 'page_obj': page_obj, "category_name": category_name,
            "categories": categories,
    }
    return render(request, 'mainapp/placelist.html', context)

def detail(request, category_name, place_id):
    place = get_object_or_404(Place, pk=place_id)
    category = get_object_or_404(Category, name=category_name)
    return render(request, 'mainapp/detail.html', {'place':place, 'category':category})

def new(request, category_name):
    category = get_object_or_404(Category, name=category_name)
    if request.method =='POST':
        form = PlaceNew(request.POST, request.FILES)
        if form.is_valid():
            place = form.save(commit=False)
            place.save()
            return redirect('/placelist/' + str(category.name) + '/' + str(place.id))
    else:
        form = PlaceNew()
        return render(request,'mainapp/new.html',{'form':form})

def update(request, place_id, category_name):
    place = get_object_or_404(Place, pk=place_id)
    category = get_object_or_404(Category, name=category_name)
    if request.method == 'POST':
        form = PlaceNew(request.POST, request.FILES, instance=place)
        if form.is_valid():
            form.save()
            return redirect('/placelist/' + str(category.name) + '/' + str(place.id))
    else:
        form = PlaceNew(instance=place)
        return render(request, 'mainapp/update.html', {'form':form})

def delete(request, category_name, place_id):
    place = Place.objects.get(pk=place_id)
    category = get_object_or_404(Category, name=category_name)
    place.delete()
    return redirect('/placelist/' + str(category.name))

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="kr">

<head>
    <meta charset="utf-8">
    <title>StudyPlace</title>
    <link rel="stylesheet" href="{% static 'mainapp/css/home.css' %}">
</head>

<body>
    <nav id="top-menu">
        <a href="{% url 'home' %}">
            <div class="logo-box">
                <img class="logo-image" src="{% static 'mainapp/images/logo.png' %}">
                <p class="logo-text1">Study</p>
                <p class="logo-text2">Place</p>
            </div>
        </a>
        <ul class="nav-link">
            <li><a href="#" class="community-link">커뮤니티</a></li>
            {% if user.is_authenticated %}
            <li><a class="login-link" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
                <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                    {% csrf_token %} <input type="hidden" />
                </form>
            </li>
            <div>환영합니다. {{ user.username }} 님!</div>
            {% else %}
            <li><a href="{% url 'accounts:login' %}" class="login-link">로그인</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
    <div class="footer">
        <div class="footer-logo-box">
            <div class="footer-logo">
                <p class="logo-text1">Study</p>
                <p class="logo-text2">Place</p>
            </div>
            <p class="copyright">Copyright©스터디플레이스</p>
        </div>
        <div class="contact-box">
            <p class="contact-text">Contact</p>
            <div>
                <img class="footer-email" src="{% static 'mainapp/images/email.png' %}">
                <img class="footer-instagram" src="{% static 'mainapp/images/instagram.png' %}">
            </div>
        </div>
    </div>
</body>

</html>

mainapp/templates/mainapp/detail.html
{% extends 'base.html' %}

{% block content %}
        <div class="body-wrapper">
            <div class="body-content">
                <h1>{{ place.name }}</h1>
                <p>{{ place.address }}</p>
                <img src="{{ place.get_photo_url }}"/>
                <a href="{% url 'mainapp:placelist' category.name %}">돌아가기</a>
                <a href="{% url 'mainapp:update' category.name place.id %}">수정</a>
                <a href="{% url 'mainapp:delete' category.name place.id %}">삭제</a>
            </div>
        </div>
{% endblock %}

mainapp/templates/mainapp/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="body-wrapper">
    <div class="body-content">
        <div>
            <span class="home-question-1">오늘의</span><span class="home-question-2"> 공부 장소</span><span
                class="home-question-1">는
                어디인가요?</span>
        </div>
        <div class="home-cafe">
            <span class="home-cafe-text">카페</span>
            <span class="home-shortcut-box">
                <a href="{% url 'mainapp:placelist' category_name='카페' %}"><span>바로가기</span></a>
                <img class="home-shortcut-img" src="{% static 'mainapp/images/next.png' %}">
            </span>
        </div>
        
        <div class="home-library">
            <span class="home-library-text">도서관</span>
            <span class="home-shortcut-box">
                <a href="{% url 'mainapp:placelist' category_name='도서관' %}"><span>바로가기</span></a>
                <img class="home-shortcut-img" src="{% static 'mainapp/images/next.png' %}">
            </span>
        </div>
        
        <div class="home-studycafe">
            <span class="home-studycafe-text">스터디카페</span>
            <span class="home-shortcut-box">
                <a href="{% url 'mainapp:placelist' category_name='스터디카페' %}"><span>바로가기</span></a>
                <img class="home-shortcut-img" src="{% static 'mainapp/images/next.png' %}">
            </span>
        </div>

    </div>
</div>

{% endblock %}

mainapp/templates/mainapp/new.html
{% extends 'base.html' %}

{% block content %}
<div class="body-wrapper">
    <div class="body-content">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <br>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
    </div>
</div>

{% endblock %}

mainapp/templates/mainapp/placelist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'mainapp/css/placelist.css' %}">

<div class="list-body-wrapper">
    <div class="list-body-content">
        <div class="place-list-box">
            <div class="list-top-box">
                <span class="list-cafe-text">카페</span>
                <span class="filter-box">
                    <img class="filter-img" src="{% static 'mainapp/images/filter.png' %}">
                    <span class="list-filter-text">필터</span>
                </span>
            </div>
            <div class="place-list">
                <li><a href="{% url 'mainapp:new' category_name %}" class="new-link">글쓰기</a></li>

                {% for place in page_obj %}
                <a href="{% url 'mainapp:detail' category_name place.id %}">
                    <div class="place-box">
                        <div class="place-img"><img src="{{ place.get_photo_url }}" /></div>
                        <div class="place-name-box">
                            <span class="place-name">{{ place.name }}</span>
                            <span class="place-rating">4.5</span>
                        </div>
                        <div class="place-short-address">{{ place.address }}</div>
                        <div class="place-view-write-box">
                            <span class="place-view-box">
                                <img class="list-view-img" src="{% static 'mainapp/images/view.png' %}">
                                <span class="list-view-count">124</span>
                            </span>
                            <span class="place-write-box">
                                <img class="list-pen-img" src="{% static 'mainapp/images/pen.png' %}">
                                <span class="list-write-count">31</span>
                            </span>
                        </div>
                    </div>
                </a>
                {% endfor %}


                <div class="pagination-box">
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}"><img class="page-arrow" src="{% static 'mainapp/images/next-left.png' %}"></a>
                    {% else %}
                    <span><img class="page-arrow" src="{% static 'mainapp/images/next-left.png' %}"></span>
                    {% endif %}

                    {% for i in page_range|default_if_none:page_obj.paginator.get_elided_page_range %}
                    {% if page_obj.number == i %}
                    <span><span class="active-page-item">{{ i }}</span></span>
                    {% else %}
                    {% if i == page_obj.paginator.ELLIPSIS %}
                    <span><span class="page-item">{{ i }}</span></span>
                    {% else %}
                    <span class="page-item"><a href="?page={{ i }}">{{ i }}</a></span>
                    {% endif %}
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><img class="page-arrow" src="{% static 'mainapp/images/next2.png' %}"></a>
                    {% else %}
                    <span><img class="page-arrow" src="{% static 'mainapp/images/next2.png' %}"></span>
                    {% endif %}
                </div>

            </div>

        </div>

        <div class="place-list-map-box">
            <div class="search">
                <input type="text" placeholder="지역 검색" style="border:0 solid black">
                <img class="magnifier-img" src="{% static 'mainapp/images/magnifier.png' %}">
            </div>
        </div>
    </div>
</div>

{% endblock %}

mainapp/templates/mainapp/update.html
{% extends 'base.html' %}

{% block content %}
<div class="body-wrapper">
    <div class="body-content">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <br>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
    </div>
</div>

{% endblock %}